language: node_js
node_js:
  #- '4'
  #- '5'
  #- '6'
  - 'node'
before_install:
  - "sudo apt-get update"
  - "sudo apt-get install cimg-dev libphash0-dev libmagickcore-dev gdb"
  - export JOBS=max
  - export prebuild_compile=true
script: "npm run build && node ./node_modules/mocha/bin/_mocha"
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
